# Generated by Django 3.1.2 on 2023-06-24 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_itemscarrito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemscarrito',
            name='NombreProducto',
        ),
        migrations.RemoveField(
            model_name='itemscarrito',
            name='PrecioProducto',
        ),
        migrations.RemoveField(
            model_name='itemscarrito',
            name='imagen',
        ),
        migrations.AddField(
            model_name='itemscarrito',
            name='cantidad_agregada',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='itemscarrito',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.producto'),
            preserve_default=False,
        ),
    ]
