# Generated by Django 3.1.2 on 2023-06-24 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_historialcompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialcompra',
            name='codigo_compra',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historialcompra',
            name='cantidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='historialcompra',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
