# Generated by Django 3.1.2 on 2023-07-09 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_auto_20230625_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateField(null=True)),
                ('nombre_completo', models.CharField(blank=True, max_length=100)),
                ('cantidad', models.IntegerField(default=0, null=True)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('comuna', models.CharField(blank=True, max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('nro_casa_departamento', models.CharField(blank=True, max_length=50)),
                ('celular', models.CharField(blank=True, max_length=100)),
                ('correo', models.CharField(blank=True, max_length=100)),
                ('comentario', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('validacion', 'Validación'), ('preparacion', 'Preparación'), ('reparto', 'Reparto'), ('entregado', 'Entregado')], default='validacion', max_length=50)),
                ('numero_pedido', models.CharField(default='', max_length=50)),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BoletaCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('precio_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('monto_neto', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('iva', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
