# Generated by Django 3.1.2 on 2023-07-12 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_boletacompra_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialcompra',
            name='codigo_compra',
        ),
        migrations.RemoveField(
            model_name='historialcompra',
            name='precio',
        ),
        migrations.AlterField(
            model_name='historialcompra',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
