# Generated by Django 3.1.2 on 2023-07-12 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20230712_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialcompra',
            name='precio',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historialcompra',
            name='cantidad',
            field=models.IntegerField(),
        ),
    ]
